#!/usr/bin/env python3
"""Produce the EMSE (Springer Nature) version from the Elsevier source.

manuscript3_revised.tex is the single source of truth for the text. This
script converts it rather than forking it, so a correction made once does not
have to be made twice and the two versions cannot drift apart.

WHAT IT CHANGES
  * document class: cas-sc -> sn-jnl with the sn-basic reference style, which
    is the author-year style EMSE uses;
  * the title block: \\cormark, \\ead, \\credit and \\affiliation become
    Springer's \\author, \\email, \\affil and an explicit author-contributions
    statement inside Declarations;
  * abstract: cas-sc's environment becomes Springer's \\abstract{} macro;
  * keywords: \\sep separators become commas;
  * highlights: removed, an Elsevier-only feature;
  * declarations: the three separate starred sections become one Declarations
    section with the subsections EMSE expects.

WHAT IT DOES NOT DO
  * It cannot compile. There is no LaTeX toolchain in this environment, so
    the output has been checked structurally and never rendered. Build it on
    Overleaf from the "Springer Nature LaTeX Template", which supplies
    sn-jnl.cls and sn-basic.bst, and read the PDF before submitting.
  * It does not add DOIs to the bibliography. Springer asks for them and 56
    references need them looked up individually; that is a manual pass.
  * It does not alphabetise the bibliography. The entries are already in
    alphabetical order by first author surname; verify after any addition.

Usage:
    python make_emse.py            # write manuscript_emse.tex
    python make_emse.py --check    # report what would change, write nothing
"""
import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "manuscript3_revised.tex")
DST = os.path.join(HERE, "manuscript_emse.tex")

PREAMBLE = r"""%% EMSE / Springer Nature version.
%%
%% GENERATED by make_emse.py from manuscript3_revised.tex. Do not edit this
%% file directly: edit the source and regenerate, or the two versions drift.
%%
%% Build on Overleaf with the "Springer Nature LaTeX Template", which supplies
%% sn-jnl.cls and sn-basic.bst. This file has never been compiled; see the
%% caveat at the top of make_emse.py.
\documentclass[sn-basic]{sn-jnl}

\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{algorithm}
\usepackage{algorithmic}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{graphicx}

\theoremstyle{thmstyleone}
\newtheorem{theorem}{Theorem}

\raggedbottom

\begin{document}

\title[Cross-corpus evaluation of query reformulation]{Cross-Corpus Evaluation
of Domain-Aware Query Reformulation for Regulatory Traceability}

\author*[1,2]{\fnm{Sumanshu} \sur{Sohal}}\email{sumanshu.95s@outlook.com}

\author[3]{\fnm{Darshankumar} \sur{Prajapati}}\email{darshan3298@gmail.com}

\affil[1]{\orgdiv{Department of Information Technology},
  \orgname{University of the Cumberlands},
  \orgaddress{\city{Williamsburg}, \postcode{40769}, \state{KY},
  \country{USA}}}

%% TODO before submission: Springer requires city and country on every
%% affiliation. Fill both in below. They are deliberately left as
%% placeholders rather than guessed.
\affil[2]{\orgname{Independent Researcher},
  \orgaddress{\city{CITY}, \country{COUNTRY}}}

\affil[3]{\orgname{Independent Researcher},
  \orgaddress{\city{CITY}, \country{COUNTRY}}}
"""

DECLARATIONS = r"""
\section*{Statements and Declarations}

\subsection*{Funding}
The authors received no funding for this work.

\subsection*{Competing interests}
The authors declare that they have no known competing financial interests or
personal relationships that could have appeared to influence the work
reported in this paper.

\subsection*{Ethics approval and consent to participate}
Not applicable. This study involves no human participants, human data or
animals.

\subsection*{Consent for publication}
Not applicable.

\subsection*{Data availability}
All four evaluation corpora are provided as supplementary material: the
diagnostic benchmark (58 requirements, 110 controls, 86 links), and the
CSF~1.1 (106 subcategories, 495 links), HIPAA Security Rule (68 requirements,
274 links) and Privacy Framework (94 subcategories, 456 links) corpora, which
share one 300-control corpus drawn from SP~800-53r5. The scripts that
regenerate the three NIST corpora from NIST's published OSCAL catalog and
crosswalk spreadsheets are included. The corpora are licensed CC BY 4.0; the
underlying NIST artifacts are United States Government works in the public
domain.

\subsection*{Materials and code availability}
The evaluation framework, all baselines, the agent implementation, the domain
thesaurus and concept patterns, the ablation and open-world harness, the
analysis scripts and the trace-export utility are available at
\url{https://github.com/sumanshusohal/RAA-Compliance-Mapping} under the MIT
Licence. The preregistration of the gated hybrid analysis is at
\url{https://doi.org/10.17605/OSF.IO/NZXRV}.

Experiments use recorded inputs, fixed seeds and fixed inference settings,
with Hugging Face model revisions pinned in every path that loads one. Exact
execution stability across hardware and software environments was not
evaluated, so we claim repeatability of our own runs rather than bitwise
reproducibility on arbitrary machines. The 30-seed logs underlying the
holdout tables are included with the release; the one-pass, factorial and
preregistered hybrid results are backed by JSON records carrying their
arguments, git commit, library versions and SHA-256 hashes of every analysis
module and input. \texttt{audit\_records.py} checks every record against the
working tree and against the commit it names, and \texttt{make\_tables.py
--check} verifies that the four primary quantitative tables in this paper
match those records.

\subsection*{Author contributions}
\textbf{Sumanshu Sohal}: conceptualization, methodology, software,
validation, formal analysis, investigation, data curation, writing --
original draft, visualization. \textbf{Darshankumar Prajapati}: methodology,
investigation, validation, writing -- review and editing.

\subsection*{Use of generative AI}
During the preparation of this work, the authors used generative AI and
AI-assisted tools to help with manuscript organization and language review,
and to assist with code review and reproducibility checking of the evaluation
harness. The authors independently verified all analyses, statistics,
citations, code and results, reviewed and edited any AI-assisted output, and
take full responsibility for the content of the publication.
"""


def convert(src):
    out = src

    # Drop the whole cas-sc title block; PREAMBLE replaces it.
    start = out.index(r"\documentclass")
    body_at = out.index(r"\begin{abstract}")
    out = PREAMBLE + "\n\n" + out[body_at:]

    # Abstract environment -> Springer macro.
    a = out.index(r"\begin{abstract}")
    b = out.index(r"\end{abstract}")
    abstract = out[a + len(r"\begin{abstract}"):b].strip()
    out = out[:a] + "\\abstract{" + abstract + "}\n" + out[b + len(r"\end{abstract}"):]

    # Highlights are Elsevier-only.
    out = re.sub(r"\\begin\{highlights\}.*?\\end\{highlights\}\s*", "",
                 out, flags=re.S)

    # Keywords: \sep -> comma, environment -> macro.
    m = re.search(r"\\begin\{keywords\}(.*?)\\end\{keywords\}", out, re.S)
    if m:
        kws = [k.strip() for k in m.group(1).split(r"\sep")]
        out = out[:m.start()] + "\\keywords{" + ", ".join(kws) + "}\n" \
            + out[m.end():]

    # Elsevier's CRediT printer has no Springer equivalent; contributions go
    # into Declarations instead.
    out = out.replace(r"\printcredits", "")

    # Replace the three starred declaration sections with one Declarations
    # block, placed where the first of them was.
    first = out.find(r"\section*{Declaration of competing interest}")
    if first != -1:
        end_marker = r"\appendix"
        end = out.index(end_marker, first)
        out = out[:first] + DECLARATIONS.strip() + "\n\n\n" + out[end:]

    # cas-sc-only commands that sn-jnl does not define.
    for cmd in (r"\let\WriteBookmarks\relax",
                r"\def\floatpagepagefraction{1}",
                r"\def\textpagefraction{.001}"):
        out = out.replace(cmd, "")

    # EMSE asks for at most three heading levels. \paragraph is LaTeX's
    # fourth, and there are nineteen of them. Promoting each to a
    # \subsubsection would satisfy the rule while adding nineteen numbered
    # headings to a paper already criticised for heading density, so they
    # become bold run-in leads instead: the same signposting, not a heading.
    out = re.sub(r"\\paragraph\{([^}]*)\}[ \t]*\n",
                 lambda m: "\\noindent\\textbf{%s}\n" % m.group(1), out)

    out = re.sub(r"\n{4,}", "\n\n\n", out)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report differences, write nothing")
    args = ap.parse_args()

    src = io.open(SRC, encoding="utf-8").read()
    out = convert(src)

    checks = [
        ("sn-jnl class", r"\documentclass[sn-basic]{sn-jnl}" in out),
        ("no cas-sc", "cas-sc" not in out.split("make_emse.py")[-1]),
        ("abstract macro", r"\abstract{" in out),
        ("no abstract env", r"\begin{abstract}" not in out),
        ("keywords macro", r"\keywords{" in out),
        ("no \\sep", r"\sep" not in out),
        ("highlights removed", r"\begin{highlights}" not in out),
        ("declarations present", r"\subsection*{Data availability}" in out),
        ("no printcredits", r"\printcredits" not in out),
        ("bibliography kept", r"\begin{thebibliography}" in out),
        ("statements heading", r"\section*{Statements and Declarations}" in out),
        ("no 4th-level headings", r"\paragraph{" not in out),
        ("affiliation is an org", r"\orgname{Independent Researcher}," in out),
    ]
    for name, ok in checks:
        print("%s %s" % ("ok  " if ok else "FAIL", name))
    failing = sum(not ok for _, ok in checks)

    if args.check:
        # The structural checks above only inspect what convert() just
        # produced. They say nothing about whether the committed EMSE file
        # still matches it, which is the drift this script exists to prevent:
        # an edit to the source, or to this converter, leaves the committed
        # output stale and --check passed anyway.
        if not os.path.exists(DST):
            print("FAIL committed EMSE file missing; run without --check")
            failing += 1
        else:
            committed = io.open(DST, encoding="utf-8").read()
            if committed == out:
                print("ok   committed file matches the converter output")
            else:
                print("FAIL committed file is stale; regenerate with "
                      "`python make_emse.py`")
                cl, ol = committed.split("\n"), out.split("\n")
                shown = 0
                for i in range(max(len(cl), len(ol))):
                    c = cl[i] if i < len(cl) else "<missing>"
                    o = ol[i] if i < len(ol) else "<missing>"
                    if c != o:
                        print("       line %d" % (i + 1))
                        print("         committed: %s" % c[:90])
                        print("         generated: %s" % o[:90])
                        shown += 1
                        if shown == 3:
                            print("       ...")
                            break
                failing += 1
        print("\n%d checks, %d failing (nothing written)"
              % (len(checks) + 1, failing))
        return 1 if failing else 0

    io.open(DST, "w", encoding="utf-8", newline="\n").write(out)
    print("\nwrote %s (%d lines)" % (os.path.relpath(DST, HERE),
                                     out.count("\n")))
    print("This file has NEVER been compiled. Build it on Overleaf with the")
    print("Springer Nature template and read the PDF before submitting.")
    return 1 if failing else 0


if __name__ == "__main__":
    sys.exit(main())
