#!/usr/bin/env python3
"""Build the EMSE (Springer SVJour3) manuscript from the Elsevier source.

manuscript3_revised.tex is the single source of truth for the text; this
converts it, so a correction made once cannot be missed in the other version.

EMSE is a Springer journal and its own FAQ points authors at an Overleaf
SVJour3 template, so the target class is svjour3, NOT the newer sn-jnl. An
earlier version of this script targeted sn-jnl, which puts \\keywords outside
the abstract and uses \\affil instead of \\institute. Neither would have
compiled correctly here.

The header follows usrguid3.pdf, the SVJour3 user's guide v3.2:

  * the format option comes first in \\documentclass, with natbib added so
    author-year citation works (guide sections 2 and 4 of the option list);
  * \\author entries separated by \\and (section 3.2);
  * \\institute repeats each author name with \\at before their address,
    commas within an address, \\and between addresses, \\email inside the
    block; a second address for the same author is a further \\at entry
    (section 3.3);
  * \\titlerunning and \\authorrunning come before \\maketitle (section 3.5);
  * \\keywords sits at the end of, but still inside, the abstract, entries
    separated by \\and (section 4);
  * \\subclass, \\PACS and \\CRclass are optional and omitted (section 4);
  * acknowledgements use the acknowledgements environment (section 6).

Output goes straight into the submission package's overleaf/ folder along
with the vendored class files, so that folder can be uploaded and compiled
as is.

Usage:
    python make_emse.py
"""
import io
import os
import re
import shutil
import sys

REPO = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.join(os.path.dirname(REPO), "EMSE submission package")
OVERLEAF = os.path.join(PKG, "overleaf")
TEMPLATE = os.path.join(REPO, "springer_template")

PREAMBLE = r"""%% Empirical Software Engineering (Springer) -- SVJour3.
%%
%% GENERATED by make_emse.py from manuscript3_revised.tex. Edit the source and
%% regenerate; edits made here are lost on the next build.
%%
%% Build with pdfLaTeX. svjour3.cls and svglov3.clo are in this folder.
%% The bibliography is an inline thebibliography, so BibTeX never runs and no
%% .bst is required; spbasic.bst is included only in case you later move to a
%% .bib file.
\RequirePackage{fix-cm}
\documentclass[smallextended,natbib]{svjour3}

\smartqed

\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{algorithm}
\usepackage{algorithmic}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{graphicx}
\usepackage{url}

\journalname{Empirical Software Engineering}

\begin{document}

\title{Cross-Corpus Evaluation of Domain-Aware Query Reformulation for
Regulatory Traceability}
\titlerunning{Cross-corpus evaluation of query reformulation}

\author{Sumanshu Sohal \and Darshankumar Prajapati}
\authorrunning{S. Sohal and D. Prajapati}

\institute{S. Sohal \at
              Department of Information Technology,
              University of the Cumberlands,
              Williamsburg, KY 40769, USA \\
              \email{sumanshu.95s@outlook.com}
           \and
           S. Sohal \at
              Independent Researcher, Washington, DC, USA
           \and
           D. Prajapati \at
              Independent Researcher, Old Bridge, NJ, USA \\
              \email{darshan3298@gmail.com}
}

% Left as the template supplies it. usrguid3 and template.tex both carry this
% literal string, and the template notes that the editor enters the real
% dates; it is not something the author fills in before submission.
\date{Received: date / Accepted: date}

\maketitle
"""

DECLARATIONS = r"""
\section*{Statements and Declarations}

\subsection*{Funding}
The authors received no funding for this work.

\subsection*{Competing interests}
The authors declare that they have no known competing financial interests or
personal relationships that could have appeared to influence the work
reported in this paper.

\subsection*{Ethics approval and consent to participate}
Not applicable. This study involves no human participants, human data or
animals.

\subsection*{Consent for publication}
Not applicable.

\subsection*{Data availability}
All four evaluation corpora are provided as supplementary material: the
diagnostic benchmark (58 requirements, 110 controls, 86 links), and the
CSF~1.1 (106 subcategories, 495 links), HIPAA Security Rule (68 requirements,
274 links) and Privacy Framework (94 subcategories, 456 links) corpora, which
share one 300-control corpus drawn from SP~800-53r5. The scripts that
regenerate the three NIST corpora from NIST's published OSCAL catalog and
crosswalk spreadsheets are included. The corpora are licensed CC BY 4.0; the
underlying NIST artifacts are United States Government works in the public
domain.

\subsection*{Materials and code availability}
The evaluation framework, all baselines, the agent implementation, the domain
thesaurus and concept patterns, the ablation and open-world harness, the
analysis scripts and the trace-export utility are available at
\url{https://github.com/sumanshusohal/RAA-Compliance-Mapping} under the MIT
Licence. The preregistration of the gated hybrid analysis is at
\url{https://doi.org/10.17605/OSF.IO/NZXRV}.

Experiments use recorded inputs, fixed seeds and fixed inference settings,
with Hugging Face model revisions pinned in every path that loads one. Exact
execution stability across hardware and software environments was not
evaluated, so we claim repeatability of our own runs rather than bitwise
reproducibility on arbitrary machines. The 30-seed logs underlying the
holdout tables are included with the release; the one-pass, factorial and
preregistered hybrid results are backed by JSON records carrying their
arguments, git commit, library versions and SHA-256 hashes of every analysis
module and input. \texttt{audit\_records.py} checks every record against the
working tree and against the commit it names, and \texttt{make\_tables.py
--check} verifies that the four primary quantitative tables in this paper
match those records.

\subsection*{Author contributions}
\textbf{Sumanshu Sohal}: conceptualization, methodology, software,
validation, formal analysis, investigation, data curation, writing --
original draft, visualization. \textbf{Darshankumar Prajapati}: methodology,
investigation, validation, writing -- review and editing.

\subsection*{Use of generative AI}
During the preparation of this work, the authors used generative AI and
AI-assisted tools to help with manuscript organization and language review,
and to assist with code review and reproducibility checking of the evaluation
harness. The authors independently verified all analyses, statistics,
citations, code and results, reviewed and edited any AI-assisted output, and
take full responsibility for the content of the publication.
"""


def convert(src):
    out = src[src.index(r"\begin{abstract}"):]

    # keywords move INSIDE the abstract, \sep -> \and (guide section 4)
    kw = re.search(r"\\begin\{keywords\}(.*?)\\end\{keywords\}", out, re.S)
    keywords = [k.strip() for k in kw.group(1).split(r"\sep")] if kw else []
    if kw:
        out = out[:kw.start()] + out[kw.end():]
    out = re.sub(r"\\begin\{highlights\}.*?\\end\{highlights\}\s*", "", out,
                 flags=re.S)
    end = out.index(r"\end{abstract}")
    out = out[:end] + "\\keywords{" + " \\and ".join(keywords) + "}\n" + out[end:]

    out = out.replace(r"\maketitle", "")
    out = out.replace(r"\printcredits", "")
    # Inline bibliography: BibTeX never runs, and Elsevier's style is not in
    # the Springer template.
    out = re.sub(r"\\bibliographystyle\{[^}]*\}\s*\n", "", out)

    # three starred declaration sections -> one Statements and Declarations
    first = out.index(r"\section*{Declaration of competing interest}")
    out = (out[:first] + DECLARATIONS.strip() + "\n\n\n"
           + out[out.index(r"\appendix", first):])

    # acknowledgements environment, stopping at the next structural command.
    # Matching lazily to \end{document} swallowed the whole bibliography,
    # because the acknowledgements sit before it and thebibliography is not a
    # \section.
    out = re.sub(
        r"\\section\*\{Acknowledgements\}\s*\n(.*?)"
        r"(?=\n\\(?:section|subsection|appendix|begin\{thebibliography\}"
        r"|end\{document\}))",
        lambda m: "\\begin{acknowledgements}\n%s\n\\end{acknowledgements}"
                  % m.group(1).strip(), out, flags=re.S)

    # \paragraph is LaTeX's fourth heading level. Keep the signposting, drop
    # the heading, which also keeps the paper inside three levels.
    out = re.sub(r"\\paragraph\{([^}]*)\}[ \t]*\n",
                 lambda m: "\\noindent\\textbf{%s}\n" % m.group(1), out)

    return PREAMBLE + "\n" + re.sub(r"\n{4,}", "\n\n\n", out)


def main():
    src = io.open(os.path.join(REPO, "manuscript3_revised.tex"),
                  encoding="utf-8").read()
    tex = convert(src)

    os.makedirs(OVERLEAF, exist_ok=True)
    io.open(os.path.join(OVERLEAF, "main.tex"), "w", encoding="utf-8",
            newline="\n").write(tex)
    io.open(os.path.join(REPO, "manuscript_emse.tex"), "w", encoding="utf-8",
            newline="\n").write(tex)
    for f in ("svjour3.cls", "svglov3.clo", "spbasic.bst"):
        shutil.copy(os.path.join(TEMPLATE, f), os.path.join(OVERLEAF, f))

    checks = [
        ("svjour3 class", r"\documentclass[smallextended,natbib]{svjour3}" in tex),
        ("journalname set", r"\journalname{Empirical Software Engineering}" in tex),
        ("keywords inside abstract",
         tex.index(r"\keywords{") < tex.index(r"\end{abstract}")),
        ("no \\sep", r"\sep" not in tex),
        ("no highlights", r"\begin{highlights}" not in tex),
        ("no Elsevier class or bst",
         "cas-model2-names" not in tex and "cas-sc" not in tex),
        ("no printcredits", r"\printcredits" not in tex),
        ("statements and declarations",
         r"\section*{Statements and Declarations}" in tex),
        ("acknowledgements environment", r"\begin{acknowledgements}" in tex),
        ("acknowledgements close before the bibliography",
         tex.index(r"\end{acknowledgements}") < tex.index(r"\begin{thebibliography}")),
        ("no fourth-level headings", r"\paragraph{" not in tex),
        ("single maketitle", tex.count(r"\maketitle") == 1),
        ("no affiliation placeholders",
         "CITY" not in tex and "COUNTRY" not in tex),
        ("environments balanced",
         all(tex.count("\\begin{%s}" % e) == tex.count("\\end{%s}" % e)
             for e in ("abstract", "acknowledgements", "thebibliography",
                       "table", "tabular", "algorithm", "description"))),
        ("every tabular width-guarded",
         tex.count(r"\begin{tabular}") == tex.count(r"\resizebox")),
    ]
    for name, ok in checks:
        print(("ok   " if ok else "FAIL "), name)
    failing = sum(not ok for _, ok in checks)
    print("\nwrote %s (%d lines) + class files" %
          (os.path.join("overleaf", "main.tex"), tex.count("\n")))
    return 1 if failing else 0


if __name__ == "__main__":
    sys.exit(main())
